package com.services.model;

import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import com.services.soap.CalculatorSoap;
/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-10-19T11:52:33.167-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "Calculator", 
                  wsdlLocation = "classpath:calculator.wsdl",
                  targetNamespace = "http://tempuri.org/") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00", comments = "Apache CXF 2.7.3")
public class Calculator extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public final static QName SERVICE = new QName("http://tempuri.org/", "Calculator");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public final static QName CalculatorSoap12 = new QName("http://tempuri.org/", "CalculatorSoap12");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public final static QName CalculatorSoap = new QName("http://tempuri.org/", "CalculatorSoap");
    static {
        URL url = Calculator.class.getClassLoader().getResource("calculator.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Calculator.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:calculator.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public Calculator(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public Calculator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public Calculator() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CalculatorSoap
     */
    @WebEndpoint(name = "CalculatorSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public CalculatorSoap getCalculatorSoap12() {
        return super.getPort(CalculatorSoap12, CalculatorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorSoap
     */
    @WebEndpoint(name = "CalculatorSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public CalculatorSoap getCalculatorSoap12(WebServiceFeature... features) {
        return super.getPort(CalculatorSoap12, CalculatorSoap.class, features);
    }
    /**
     *
     * @return
     *     returns CalculatorSoap
     */
    @WebEndpoint(name = "CalculatorSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public CalculatorSoap getCalculatorSoap() {
        return super.getPort(CalculatorSoap, CalculatorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorSoap
     */
    @WebEndpoint(name = "CalculatorSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.167-05:00")
    public CalculatorSoap getCalculatorSoap(WebServiceFeature... features) {
        return super.getPort(CalculatorSoap, CalculatorSoap.class, features);
    }

}
