package com.services.soap;

import javax.annotation.Generated;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

import com.services.model.Add;
import com.services.model.AddResponse;
import com.services.model.Divide;
import com.services.model.DivideResponse;
import com.services.model.Multiply;
import com.services.model.MultiplyResponse;
import com.services.model.ObjectFactory;
import com.services.model.Subtract;
import com.services.model.SubtractResponse;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-10-19T11:52:33.021-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CalculatorSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00", comments = "Apache CXF 2.7.3")
public interface CalculatorSoap {

    @WebMethod(operationName = "Subtract")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Response<SubtractResponse> subtractAsync(
        @WebParam(partName = "parameters", name = "Subtract", targetNamespace = "http://tempuri.org/")
        Subtract parameters
    );

    @WebMethod(operationName = "Subtract")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Future<?> subtractAsync(
        @WebParam(partName = "parameters", name = "Subtract", targetNamespace = "http://tempuri.org/")
        Subtract parameters,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SubtractResponse> asyncHandler
    );

    @WebMethod(operationName = "Subtract", action = "http://tempuri.org/Subtract")
    @WebResult(name = "SubtractResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public SubtractResponse subtract(
        @WebParam(partName = "parameters", name = "Subtract", targetNamespace = "http://tempuri.org/")
        Subtract parameters
    );

    @WebMethod(operationName = "Divide")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Response<DivideResponse> divideAsync(
        @WebParam(partName = "parameters", name = "Divide", targetNamespace = "http://tempuri.org/")
        Divide parameters
    );

    @WebMethod(operationName = "Divide")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Future<?> divideAsync(
        @WebParam(partName = "parameters", name = "Divide", targetNamespace = "http://tempuri.org/")
        Divide parameters,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DivideResponse> asyncHandler
    );

    @WebMethod(operationName = "Divide", action = "http://tempuri.org/Divide")
    @WebResult(name = "DivideResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public DivideResponse divide(
        @WebParam(partName = "parameters", name = "Divide", targetNamespace = "http://tempuri.org/")
        Divide parameters
    );

    @WebMethod(operationName = "Add")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Response<AddResponse> addAsync(
        @WebParam(partName = "parameters", name = "Add", targetNamespace = "http://tempuri.org/")
        Add parameters
    );

    @WebMethod(operationName = "Add")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Future<?> addAsync(
        @WebParam(partName = "parameters", name = "Add", targetNamespace = "http://tempuri.org/")
        Add parameters,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AddResponse> asyncHandler
    );

    /**
     * Adds two integers. This is a test WebService. ©DNE Online
     */
    @WebMethod(operationName = "Add", action = "http://tempuri.org/Add")
    @WebResult(name = "AddResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public AddResponse add(
        @WebParam(partName = "parameters", name = "Add", targetNamespace = "http://tempuri.org/")
        Add parameters
    );

    @WebMethod(operationName = "Multiply")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Response<MultiplyResponse> multiplyAsync(
        @WebParam(partName = "parameters", name = "Multiply", targetNamespace = "http://tempuri.org/")
        Multiply parameters
    );

    @WebMethod(operationName = "Multiply")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public Future<?> multiplyAsync(
        @WebParam(partName = "parameters", name = "Multiply", targetNamespace = "http://tempuri.org/")
        Multiply parameters,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<MultiplyResponse> asyncHandler
    );

    @WebMethod(operationName = "Multiply", action = "http://tempuri.org/Multiply")
    @WebResult(name = "MultiplyResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-10-19T11:52:33.021-05:00")
    public MultiplyResponse multiply(
        @WebParam(partName = "parameters", name = "Multiply", targetNamespace = "http://tempuri.org/")
        Multiply parameters
    );
}
